apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: echo
    app.kubernetes.io/instance: echo
  name: echo
spec:
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app.kubernetes.io/name: echo
    app.kubernetes.io/instance: echo
  type: ClusterIP
