apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: orca
    app.kubernetes.io/instance: orca
  name: orca
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app.kubernetes.io/name: orca
    app.kubernetes.io/instance: orca
  type: ClusterIP
