apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: front50
    app.kubernetes.io/instance: front50
  name: front50
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: front50
    app.kubernetes.io/instance: front50
  type: ClusterIP
