apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=80.0
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: gcr.io/spinnaker-marketplace/echo:spinnaker-master-latest-validated
        name: echo
        ports:
        - name: traffic-port
          containerPort: 8089
          protocol: TCP
        readinessProbe:
          httpGet:
            port: traffic-port
            path: /health
        resources:
          requests:
            cpu: 800m
            memory: 1200Mi
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: echo-config-volume
        - mountPath: /var/secrets
          name: spinnaker-secrets-volume
      terminationGracePeriodSeconds: 720
      volumes:
      - name: echo-config-volume
        secret:
          secretName: echo-config
      - name: spinnaker-secrets-volume
        secret:
          secretName: spinnaker-secrets
