apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ignored
spec:
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=80.0
        image: gcr.io/spinnaker-marketplace/monitoring-daemon:spinnaker-master-latest-validated
        name: monitoring-daemon
        ports:
        - containerPort: 8008
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8008
        volumeMounts:
        - mountPath: /opt/spinnaker-monitoring/filters
          name: spinnaker-monitoring-filters-volume
        - mountPath: /opt/spinnaker-monitoring/config
          name: spinnaker-monitoring-config-volume
        - mountPath: /opt/spinnaker-monitoring/registry
          name: spinnaker-monitoring-registry-volume
        - mountPath: /var/secrets
          name: spinnaker-secrets-volume
