apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./clouddriver
- ./echo
- ./fiat
- ./front50
- ./igor
- ./gate
- ./orca
commonLabels:
  app.kubernetes.io/component: server
  app.kubernetes.io/managed-by: kleat
  app.kubernetes.io/part-of: spinnaker
  app.kubernetes.io/version: 1.18.2
secretGenerator:
- behavior: merge
  files:
  - config/spinnaker.yml
  name: clouddriver-config
- behavior: merge
  files:
  - config/spinnaker.yml
  name: echo-config
- behavior: merge
  files:
  - config/spinnaker.yml
  name: fiat-config
- behavior: merge
  files:
  - config/spinnaker.yml
  name: front50-config
- behavior: merge
  files:
  - config/spinnaker.yml
  name: gate-config
- behavior: merge
  files:
  - config/spinnaker.yml
  name: igor-config
- behavior: merge
  files:
  - config/spinnaker.yml
  name: orca-config
- files: []
  name: spinnaker-secrets
namespace: spinnaker
