apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./clouddriver
- ./echo
- ./fiat
- ./front50
- ./igor
- ./gate
- ./orca
secretGenerator:
- behavior: merge
  files:
  - ../service_discovery/spinnaker.yml
  name: clouddriver-config
- behavior: merge
  files:
  - ../service_discovery/spinnaker.yml
  name: echo-config
- behavior: merge
  files:
  - ../service_discovery/spinnaker.yml
  name: fiat-config
- behavior: merge
  files:
  - ../service_discovery/spinnaker.yml
  name: front50-config
- behavior: merge
  files:
  - ../service_discovery/spinnaker.yml
  name: gate-config
- behavior: merge
  files:
  - ../service_discovery/spinnaker.yml
  name: igor-config
- behavior: merge
  files:
  - ../service_discovery/spinnaker.yml
  name: orca-config
