apiVersion: apps/v1
kind: Deployment
metadata:
  name: igor
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=80.0
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: gcr.io/spinnaker-marketplace/igor:spinnaker-master-latest-unvalidated
        name: igor
        ports:
        - name: traffic-port
          containerPort: 8088
          protocol: TCP
        readinessProbe:
          httpGet:
            port: traffic-port
            path: /health
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: igor-config-volume
        - mountPath: /var/secrets
          name: spinnaker-secrets-volume
      terminationGracePeriodSeconds: 720
      volumes:
      - name: igor-config-volume
        secret:
          secretName: igor-config
      - name: spinnaker-secrets-volume
        secret:
          secretName: spinnaker-secrets
